CHANGELOG.rst, setup.py
=> Prepare release.

cliquet_fxa/authentication.py, cliquet_fxa/tests/test_authentication.py
See https://github.com/mozilla-services/cliquet/issues/299
=> Do not prefix userid, cliquet now handles it

CHANGELOG.rst, README.rst, cliquet_fxa/__init__.py, cliquet_fxa/authentication.py, cliquet_fxa/tests/test_authentication.py, cliquet_fxa/tests/test_includeme.py, cliquet_fxa/tests/test_views.py, cliquet_fxa/views/params.py, cliquet_fxa/views/relier.py, setup.py
=> Handle new token and mandatory bearer token scopes — Fixes Kinto/kinto#204

.coveragerc, CHANGELOG.rst, cliquet_fxa/tests/test_views.py, cliquet_fxa/views/relier.py
Here: https://github.com/mozilla-services/cliquet-fxa/blob/master/cliquet_fxa/views/relier.py#L74
=> Replace space in scopes by +

cliquet_fxa/__init__.py, cliquet_fxa/tests/test_views.py, setup.py
Based on https://github.com/mozilla-services/cliquet/pull/481 to handle https://github.com/mozilla-services/cliquet-fxa/pull/12/files#diff-741c1cf20a0af1d2341a7afa5a07ca0cR76
=> Support for Cliquet 2.8.2+

CHANGELOG.rst, setup.py
=> Preparing release 1.3.2

CHANGELOG.rst, setup.py
=> Preparing release 1.4.0

cliquet_fxa/tests/test_views.py
=> Update tests with new settings.

CHANGELOG.rst, cliquet_fxa/authentication.py
=> Fix checking of Authorization header with python -O (ref mozilla-services/cliquet#592)

README.rst
... just in case anyone was looking for it.
=> explain what happened to cliquet-fxa

CONTRIBUTORS.rst, kinto_fxa/__init__.py, kinto_fxa/tests/test_views.py
=> Fixed Isse: #23: Add the fxa capability on the hello page

CHANGELOG.rst, Makefile, kinto_fxa/__init__.py, kinto_fxa/tests/test_views.py, setup.py
Refs https://github.com/Kinto/kinto/issues/591
r? @tarekziade
=> Add kinto-fxa plugin version in the capability.

.travis.yml, CHANGELOG.rst, kinto_fxa/tests/__init__.py, kinto_fxa/tests/test_authentication.py, kinto_fxa/tests/test_includeme.py, kinto_fxa/tests/test_views.py, setup.py, tox.ini
=> Preparing release 2.1.0

setup.py
Current schema validation is not compatible with Cornice 2 :)
=> Not compatible with Cornice 2

CHANGELOG.rst, kinto_fxa/__init__.py, kinto_fxa/authentication.py, kinto_fxa/tests/__init__.py, kinto_fxa/tests/test_authentication.py, kinto_fxa/tests/test_views.py
=> Reify token validation (fixes #33)

CHANGELOG.rst, setup.py
=> Prepare 2.2.0

kinto_fxa/tests/test_views.py, kinto_fxa/views/relier.py
I was removed the permissions to push to mozilla-services. Hence the PR.
=> Fix compatibility with Cornice 2

.coveragerc, kinto_fxa/tests/test_authentication.py, kinto_fxa/tests/test_views.py, kinto_fxa/views/relier.py, setup.py
=> Migrate schemas to Cornice 2

CHANGELOG.rst, README.rst, kinto_fxa/scripts/__main__.py, kinto_fxa/scripts/process_account_events.py, kinto_fxa/tests/test_authentication.py, kinto_fxa/tests/test_process_account_events.py, kinto_fxa/tests/test_scripts_main.py, setup.py, tox.ini
This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1461998.
=> Introduce process-account-events script

CHANGELOG.rst, setup.py
- Introduce new ``kinto_fxa.scripts``. Right now the only script
available is ``process-account-events``, which listens to an SQS
queue for user delete events and deletes data from that user's
default bucket, in order to comply with GDPR.
=> Preparing release 2.5.0

CHANGELOG.rst, kinto_fxa/scripts/process_account_events.py, kinto_fxa/tests/test_process_account_events.py
=> Fix the ``process-account-events`` script to take client user ID suffixes into account (fixes #61)

kinto_fxa/authentication.py, requirements.txt
=> Less instantiation of OAuthClient
